# Dataset reader arguments
dataset:
  image_features_train_h5: 'data/features_vgg16_fc7_train.h5'
  image_features_val_h5: 'data/features_vgg16_fc7_val.h5'
  image_features_test_h5: 'data/features_vgg16_fc7_test.h5'
  word_counts_json: 'data/visdial_1.0_word_counts_train.json'

  img_norm: 1
  concat_history: true
  max_sequence_length: 20
  vocab_min_count: 5


# Model related arguments
model:
  encoder: 'lf'
  decoder: 'disc'

  img_feature_size: 4096
  word_embedding_size: 300
  lstm_hidden_size: 512
  lstm_num_layers: 2
  dropout: 0.5


# Optimization related arguments
solver:
  batch_size: 32
  num_epochs: 20
  initial_lr: 0.001
  lr_gamma: 0.9997592083
  minimum_lr: 0.00005
  training_splits: "train"  # "trainval"

